### ISSUE TITLE
For: blRunJS

### ISSUE THREAD

**Issue by littleflute** [littleflute/JavaScript#10]

**Comment by littleflute** [comment]
function f1(){
//f1
}

**Comment by littleflute** [comment]
function f2(){
//f1
}

**Comment by littleflute** [comment]
//js3:
var m = this.parentElement.parentElement.parentElement.parentElement;
if(!m.n) m.n = 0;
m.style.background = blColor[m.n];
m.n++;
if(m.n>=blColor.length) m.n = 0;

**Comment by littleflute** [comment]
//js4:
var m = document.getElementsByTagName("audio");
if(!m.plx){
    m.plx = blo0.blMDiv(document.body,"id_mdiv_auio1_plx","auio1Plx",300,100,300,200,blGrey[0]);
m.plx.v = blo0.blDiv(m.plx,m.plx.id+"v","v",blGrey[1]);
}

**Comment by littleflute** [comment]
var m = document.getElementsByTagName("audio");
var p = m[0];
bl$("title4api2").innerHTML = p.id;

**Comment by littleflute** [comment]
var lrcTimer0;
var lrcTimer1;
var xdMin;
function _golrcolor(t)
  { 
    if(t<=10)
      lrcTimer1 = setTimeout("_golrcolor("+t+")",xdMin*10);
  }
  function _blMove(s,_o)
  { 
	_o.style.top = -(s++)*2;
	if(s<=9)
		lrcTimer0 = setTimeout("_blMove("+s+","+_o+")",xdMin*10);
  }
    
function blLrcClass ( blDivBoss , tt , _nIdx , blID )
{	
	var xdVer	= " blLrcClass :: v1.1. 255 "; 

  var _CreateUI = function( _oBoss , _id )
  {  
	var d 	= blo0.blDiv( _oBoss , "id_div_4_Lyric_ui" + blID  , blID ,blColor[3]); 
	var divMP = blo0.blDiv(d, "mp1" + blID ,"xdxdxd","red"); 
	_InitPlayer(xdType,divMP, _id ); 
	var xddbgDiv = o.blDiv(d,"xddbgLyric" + blID ,xdVer,"gold");
	var MyTimer = o.blDiv(d,"idMyTimer" +blID  , "timer:" );
	_CreateLyrBoard2(d);
  }
  var _CreateLyrBoard2 = function(oBoss)
  {	 
		var d2Body = o.blDiv(oBoss,"d2Body"+ blID ,"","DarkOrchid");
		_CreateToolBar(d2Body);
		var d1 = o.blDiv(oBoss,oBoss.id+"_div_song_right_now",QueryString.f,blColor[2]); 
		var url = QueryString.l;
		var d2 = o.blDiv(oBoss,oBoss.id+"_div_lrc_right_now",url,blColor[4]); 
		var lrcLink = blo0.blLink(oBoss,oBoss.id+"lrcLink","lrc_src",url,blColor[3]); 
		
		var d2BodyContend = o.blDiv(oBoss,"d2BodyContend"+ blID ,"d2BodyContend: V x.x.x",blColor[12]); 

		var s = "";
		s += '<div style="overflow:hidden; height:260; width:660; background-color:#59a;">'; 
		s += '<table border="1" cellspacing="0" cellpadding="0" width="100%" id="lrcoll'+blID+'"';
		s += ' style="position:relative; top: -20px;" oncontextmenu="return false;">';
		s += '<tr><td nowrap height="20" align="center" id="lrcwt1'+blID+'"></td></tr>';
		s += '<tr><td nowrap height="20" align="center" id="lrcwt2'+blID+'"></td></tr>';
		s += '<tr><td nowrap height="20" align="center" id="lrcwt3'+blID+'"></td></tr>';
		s += '<tr><td nowrap height="20" align="center" id="lrcwt4'+blID+'"></td></tr>';
		s += '<tr><td nowrap height="20" align="center" id="lrcwt5'+blID+'"></td></tr>';
		s += '<tr style="color:#BDB76B;">';
			s += '<td nowrap height="20" align="center" id="lrcwt6'+blID+'">';
				s += '</td></tr>'; 

		s += '<tr style="color:#BDB76B;">';
			s += '<td nowrap height="20" align="center">';
					s += '<div id="lrcwt7'+blID+'" style="overflow:hidden;position:relative; width:100%; color:#FFFF33; height:20">lrcwt7 ...</div>';
					s += '<div id="lrcfilter'+blID+'" style="overflow:hidden;position:relative;top: -20px; width:100%; color:#FFFF33; height:20">lrcfilter ...</div>';
				s += '</td></tr>'; 

		s += '<tr style="color:#BDB76B;">';
			s += '<td nowrap height="20">';
					s += '<div>';
					s += '<div id="lrcbox'+blID+'" style="overflow:hidden;position:relative; width:100%; color:#800000; height:20">?豕∩那?車???D ...</div>';
					s += '<div id="idMovingLyr'+blID+'" style="overflow:hidden;position:relative;top: -20px; width:0; color:#FFFF33; height:20">?豕∩那?車???D ...</div>';
					s += '</div>';
				s += '</td></tr>'; 
 
		s += '<tr style="position:relative; top: -20px;color:#FF9900;">';
			s += '<td nowrap height="20" align="center" id="lrcwt8'+blID+'"></td>';
		s += '</tr>';
		s += '<tr style="position:relative; top: -20px;"><td nowrap height="20" align="center" id="lrcwt9'+blID+'"></td></tr>';
		s += '<tr style="position:relative; top: -20px;"><td nowrap height="20" align="center" id="lrcwtA'+blID+'"></td></tr>';
		s += '<tr style="position:relative; top: -20px;"><td nowrap height="20" align="center" id="lrcwtB'+blID+'"></td></tr>';
		s += '<tr style="position:relative; top: -20px;"><td nowrap height="20" align="center" id="lrcwtC'+blID+'"></td></tr>';
		s += '<tr style="position:relative; top: -20px;"><td nowrap height="20" align="center" id="lrcwtD'+blID+'"></td></tr>';
		s += '</table>';
		s += '</div>';
		
		d2BodyContend.innerHTML = s;
  } 
	var _currentTime = 0;

  	var nMyTimer = 0;
  this.TimerFun = function(_this)
  {
		return function(){ 
			var d = document.getElementById("idMyTimer" + blID );
			var s = " ";//d.innerHTML;
			s += "_currentTime=";
			s += _currentTime;
			s += " nMyTimer= ";
			nMyTimer++;
			s += nMyTimer;
			var playerObj = document.getElementById("idLyricMP");
			s += " blVMP.blrGetCP = " + blVMP.blrGetCP(); 
			s += "<br>";
			d.innerHTML = s;
			_this.xdRun(playerObj);
		}
  }(this);
 
	this.blrAboutMe = function(b,d){		
		var s = "";
		s += "<a target='_blank' href='https://github.com/littleflute/beautifullover.org/edit/master/blLrc.js'"
		s += " style='color:lightblue;'";
		s +=">";
		s += " blLrc.js*  ";
		s += "</a>"; 
		s += "<a target='_blank' href='blLrc.js'"
		s += " style='color:yellow;'";
		s +=">";
		s += " blLrc.js ";
		s += "</a>"; 
		d.innerHTML = s;
		_on_off_div(b,d);
	}

	this.blrMakeStamp = function(b,d){ 
		d.innerHTML = xdVer;
		var ta = blo0.blTextarea(d,d.id+"ta","v",blColor[11]);
		ta.style.width = "100%";
		ta.style.height = "50px";
		var v = blo0.blDiv(d,d.id+"v","v",blColor[1]);
		var b1 = blo0.blBtn(d,d.id+"b1","b1",blColor[8]);
		b1.onclick = function(v_){
			var n = 0;
			return function(){
				n++;
				var l = document.getElementById("lrcdata");
				if(1){
					v_.innerHTML = n + "㏒o" + _currentTime + "";
					ta.value = l.innerHTML;
				}
			}
		}(v);
		_on_off_div(b,d);
	};
	
	this.bll1 = "bll1--------";
  
	var xdType = 3;

	var o = new blClass;
	var blVMP = new _blVMPlayer;	
   
	function _InitPlayer(t,oDivBoss, _id ) { 
		switch(t)
		{
		case 3:
			oDivBoss.innerHTML = "ID: " + _id ;
			blVMP.blrPlay();
			break;  
		} 
	}
  var _CreateToolBar = function(oBoss)
  {	
		var d = o.blDiv(oBoss,oBoss.id+"_div_ToolBar","_div_ToolBar: v0.0.7","white");
		var b1 = o.blBtn(d,d.id+"_btn_b1","+","red"); 
		b1.onclick = function(btn_){
			var v = null;
			return function(){
				v = o.blDiv(d,btn_.id+"_div_View","b1v","green");
				o.blShowObj2Div(v,lrcobj);
				_on_off_bd(btn_,v);
			}
		}(b1);
  }

  _CreateUI ( blDivBoss , blID );

  this.inr = [];
  this.min = [];
  this.oTime = 0;
  this.dts = -1;
  this.dte = -1;
  this.dlt = -1;
  this.ddh;
  this.fjh;
  bl$("idMovingLyr"+blID).style.width = 0;
  if(/\[offset\:(\-?\d+)\]/i.test(tt))
    this.oTime = RegExp.$1/1000;

  tt = tt.replace(/\[\:\][^$\n]*(\n|$)/g,"$1");
  tt = tt.replace(/\[[^\[\]\:]*\]/g,"");
  tt = tt.replace(/\[[^\[\]]*[^\[\]\d]+[^\[\]]*\:[^\[\]]*\]/g,"");
  tt = tt.replace(/\[[^\[\]]*\:[^\[\]]*[^\[\]\d\.]+[^\[\]]*\]/g,"");
  tt = tt.replace(/<[^<>]*[^<>\d]+[^<>]*\:[^<>]*>/g,"");
  tt = tt.replace(/<[^<>]*\:[^<>]*[^<>\d\.]+[^<>]*>/g,"");


  while(/\[[^\[\]]+\:[^\[\]]+\]/.test(tt))
  {
    tt = tt.replace(/((\[[^\[\]]+\:[^\[\]]+\])+[^\[\r\n]*)[^\[]*/,"\n");
    var zzzt = RegExp.$1;
    /^(.+\])([^\]]*)$/.exec(zzzt);
    var ltxt = RegExp.$2;
    var eft = RegExp.$1.slice(1,-1).split("][");
    for(var ii=0; ii<eft.length; ii++)
    {
      var sf = eft[ii].split(":");
      var tse = parseInt(sf[0],10) * 60 + parseFloat(sf[1]);
      var sso = { t:[] , w:[] , n:ltxt }
      sso.t[0] = tse-this.oTime;
      this.inr[this.inr.length] = sso;
    }
  }

  this.inr = this.inr.sort( function(a,b){return a.t[0]-b.t[0];} ); 

  for(var ii=0; ii<this.inr.length; ii++)
  {
    while(/<[^<>]+\:[^<>]+>/.test(this.inr[ii].n))
    {
      this.inr[ii].n = this.inr[ii].n.replace(/<(\d+)\:([\d\.]+)>/,"%=%");
      var tse = parseInt(RegExp.$1,10) * 60 + parseFloat(RegExp.$2);
      this.inr[ii].t[this.inr[ii].t.length] = tse-this.oTime;
    }

    bl$("idMovingLyr"+blID).innerHTML = "<font>"+ this.inr[ii].n.replace(/&/g,"&").replace(/</g,"<").replace(/>/g,">").replace(/%=%/g,"</font><font>") +"</font>";
 
    var fall = bl$("idMovingLyr"+blID).getElementsByTagName("font");
    for(var wi=0; wi<fall.length; wi++)
      this.inr[ii].w[this.inr[ii].w.length] = fall[wi].offsetWidth;
  }


  for(var ii=0; ii<this.inr.length-1; ii++)
    this.min[ii] = Math.floor((this.inr[ii+1].t[0]-this.inr[ii].t[0])*10);

  this.min.sort(function(a,b){return a-b});
  xdMin = this.min[0]/2;

  var nXdDbgNum = 0;
  this.xdRun = function(xdMP)
  { 
	nXdDbgNum++;
	var xdCP;
	switch(xdType)
	{
	case 3: 
		xdCP = blVMP.blrGetCP(); 		
		break;
	case 4:
		xdCP = xdMP.controls.currentPosition;  
		break;
	case 5:
		xdCP = xdMP.currentTime;  
		break;
	} 
	_currentTime = xdCP;

    if(xdCP<this.dts || xdCP>=this.dte)
    {	
      var ii;
      for(ii=this.inr.length-1; ii>=0 && this.inr[ii].t[0]>xdCP; ii--){}
      if(ii<0) 
	  { 
			return;
	  }
 
      this.ddh = this.inr[ii].t;
      this.fjh = this.inr[ii].w;
      this.dts = this.inr[ii].t[0];
      this.dte = (ii<this.inr.length-1)?this.inr[ii+1].t[0]:xdCP;

      bl$("lrcwt1"+blID).innerText = this.retxt(ii-7);
      bl$("lrcwt2"+blID).innerText = this.retxt(ii-6);
      bl$("lrcwt3"+blID).innerText = this.retxt(ii-5);
      bl$("lrcwt4"+blID).innerText = this.retxt(ii-4);
      bl$("lrcwt5"+blID).innerText = this.retxt(ii-3);
      bl$("lrcwt6"+blID).innerText = this.retxt(ii-2);
  
      bl$("lrcwt7"+blID).innerText			= this.retxt(ii-1);
      bl$("lrcfilter"+blID).innerText		= this.retxt(ii-1);

      bl$("lrcwt8"+blID).innerText		= ">>>-"  + this.retxt(ii+1);
      bl$("lrcwt9"+blID).innerText		= this.retxt(ii+2);
      bl$("lrcwtA"+blID).innerText = this.retxt(ii+3);
      bl$("lrcwtB"+blID).innerText = this.retxt(ii+4);
      bl$("lrcwtC"+blID).innerText = this.retxt(ii+5);
      bl$("lrcwtD"+blID).innerText = this.retxt(ii+6);
      this.blSetTxt(this.retxt(ii)); 

      if(this.dlt==ii-1)
      {
        clearTimeout(lrcTimer0);
        if(bl$("lrcoll"+blID).style.pixelTop!=0) bl$("lrcoll"+blID).style.top = 0;
  
		_blMove(0,"lrcoll"+blID);  
        clearTimeout(lrcTimer1);  
        _golrcolor(0); 
      }
      else if(parseInt(bl$("lrcoll"+blID).style.top)!=-20)
      {
	    clearTimeout(lrcTimer0);
        bl$("lrcoll"+blID).style.top = -20;
        clearTimeout(lrcTimer1);
      }

      this.dlt = ii; 
    }

    var bbw = 0;
    var ki;
    for(ki=0; ki<this.ddh.length && this.ddh[ki]<=xdCP; ki++)
      bbw += this.fjh[ki];
    var kt = ki-1;
    var sc = ((ki<this.ddh.length)?this.ddh[ki]:this.dte) - this.ddh[kt];
    var tc = xdCP - this.ddh[kt];
    bbw -= this.fjh[kt] - tc / sc * this.fjh[kt];
    if(bbw>bl$("lrcbox"+blID).offsetWidth)
      bbw = bl$("lrcbox"+blID).offsetWidth;
    bl$("idMovingLyr"+blID).style.width = Math.round(bbw);
  }

  this.retxt = function(i)
  {
    return (i<0 || i>=this.inr.length)?"xxxxxxxx":this.inr[i].n;
  }

  this.blSetTxt = function(txt)
  {
    bl$("lrcbox"+blID).innerText		= txt;
    bl$("idMovingLyr"+blID).innerText	= txt;
  }
  
  this.blSetTxt("?米赤3?Y??車D?角1??豕∩那...");
  bl$("lrcwt1"+blID).innerText = "111111111111111111";
  bl$("lrcwt2"+blID).innerText = "";
  bl$("lrcwt3"+blID).innerText = "";
  bl$("lrcwt4"+blID).innerText = "";
  bl$("lrcwt5"+blID).innerText = "";
  bl$("lrcwt6"+blID).innerText = ""; 
  bl$("lrcwt7"+blID).innerText = "";
  bl$("lrcfilter"+blID).innerText = "***************==";
  bl$("lrcwt8"+blID).innerText = "";
  bl$("lrcwt9"+blID).innerText = "";
  bl$("lrcwtA"+blID).innerText = "";
  bl$("lrcwtB"+blID).innerText = "";
  bl$("lrcwtC"+blID).innerText = "";
  bl$("lrcwtD"+blID).innerText = "";
	 
  this.blRun = function(_this)
  {
		return function(_this){
			setInterval(_this.TimerFun,10);
		}
  }(this); 
}//END: blLrcClass

function _blVMPlayer()
{
	var nTime = 0; 
	var _myFun = function(_this){
		return function(){			//nTime += 0.01;
			var x = document.getElementsByTagName("audio");
			nTime = x[0].currentTime;
		}
	}(this);

	this.blrPlay = function()	{	setInterval(_myFun,10);	}
	this.blrGetCP = function()	{	return nTime;	}
}

**Comment by littleflute** [comment]
var b = bl$("blrToolBar");
var p = b.parentElement.parentElement;
p.style.zIndex = 1000;

**Comment by littleflute** [comment]
var blPink = [
"Pink",// #FFC0CB
"LightPink", // #FFB6C1
];

**Comment by littleflute** [comment]
var p = bl$("id_div_4_api2_v");
p.v1 = blo0.blDiv(p,p.id+"v1","v1","blue");

**Comment by littleflute** [comment]
//blo0.blAjx(worker,url);  unit Test
var w = {};
w._2do = function(txt){
    alert(txt);
}
var urlLrc = "https://littleflute.github.io/english/NewConceptEnglish/Book2/1.lrc"
blo0.blAjx(w,urlLrc);

**Comment by littleflute** [comment]
//test for:  https://api.github.com/repos/littleflute/english/issues/26
var x = bl$("blrMp3ListDivv4List _title_v");

x.currentTimeFun = function(){
 x.d2 = blo0.blDiv(x,x.id+"d2", "d2",blColor[4]);
          x.d2.innerHTML =  bl$("id_mp3Player").currentTime;
}

**Comment by littleflute** [comment]
var t1 = bl$("blah");
var d1 = bl$("id_blClassDiv_4_wrap1");
t1.value = "2215";
d1.showVextab ();

**Comment by littleflute** [comment]
var m = document.getElementsByTagName("textarea");
var p = m[0];
alert(p.value);

**Comment by littleflute** [comment]
function str(n1,n2){
  var rs = "";
  for(var i = n1; i<n2+1;i++){
    var item = "[" + i + "]" + "(" + i + ") ";
    rs += item;
  }
  alert(rs);
}
str(61,70);

**Comment by shanuan** [comment]
var d1 = bl$("DivButtons");

var d = blo0.blMDiv(document.body,"xd3", d1.innerHTML,    300,100,500,400, blGrey[5]); 

_on_off_div(null,d);

**Comment by littleflute** [comment]
var s = "";
 var n1 = 177;
 var n = 5;
 var nn = 0;
  function _loadIssue (o) { 
     nn++; 
     s += "\n Chapter " + nn + "\n";
     s += o.body;  
     if(n==nn)alert(s);  
  }
 for(var i = n1; i<n1+n; i++){
  var url = "https://api.github.com/repos/littleflute/english/issues/" + i;
  w3.getHttpObject(url, _loadIssue ); 
}

**Comment by littleflute** [comment]
var a= location; 
a = a.toString(); 
var b = a.replace(/\//g,"\\");
var c = b.split("\\\\\\");
var d = c[1]; 
var e = d.split("\\index");
alert(e[0]);

**Comment by AlphaSylan** [comment]
var md = blo0.blDiv(document.body, "idMD","idMD",blGrey[0]);  
 
	var style ="position: absolute;";
	style += "z-index: 9;";
	style += "background-color: #f1f1f1;";
	style += "text-align: center;";
	style += "border: 1px solid #d3d3d3;";
	style += "left: 400px";
	style += "top: 40px";
	md .style =style;

	var title = blo0.blDiv(md ,"moveDivHeader","header");
	style ="padding: 10px;";
	style += "z-index: 10;";
	style += "cursor: move;";
	style += "text-align: center;";
	style += "border: 1px solid #fff;";
	style += "background-color: #2196F3;";
	title.style =style;
blo0.blMakeDivMovable(md );

**Comment by littleflute** [comment]
var s = "test4: setInterval & clearInterval";
var d = blo0.blMDiv(document.body,"id_mdiv_Timer", s,300,100,500,400, blGrey[5]); 
 d.tb = blo0.blDiv(d, d.id + "tb", "tb", blGrey[1]);
 d.v = blo0.blDiv(d, d.id + "v", "v:", blGrey[2]);
 d.tb.b1 = blo0.blBtn(d.tb, d.tb.id + "b1", "b1", blGrey[0]);
var btn =  d.tb.b1;  var v = d.v;
btn.onclick = function run(_this, _v) {
 var r = false; 
 var n = 0;
 var t = null;  
 return function(){
  if(!r){
     t = setInterval(myTimer ,100);
  	r=true;
  }
  else{
    clearInterval(t); 
    n = 0;
    _v.innerHTML = n;
    r=false;
  }
   
   function myTimer() {
       n++;
       _v.innerHTML = n;
   }
 }
}(btn,v);
_on_off_div(null,d);

**Comment by littleflute** [comment]
var s = "xdtest: v0.0. 11 ";
var d = blo0.blMDiv(document.body,"xd5", s,700,100,500,400, blGrey[5]);  
for(var i = 0; i<10;i++){
    var v = blo0.blDiv(d, d.id+ "v" + i, i, blGrey[0]);
    for(var j = 0; j<10;j++){
        var b = blo0.blBtn(v, v.id + "b" + j, j, blGrey[3]);
        b.onclick = function(_i,_j){
            return function(){
                 alert(_i+","+_j);
            }
        }(i,j);
    }
}

_on_off_div(this,d);

**Comment by littleflute** [comment]
blo0.blScript("id_js_blCChessBoard.js","https://littleflute.github.io/cchess0/cchess/blCChessBoard.js");

**Comment by littleflute** [comment]
var b = bl$("id_div_4_api2_vv1_btn_1");
b.onclick = function(){
  if(!this.load){
      this.load = true;
      blo0.blScript("id_script_4_c4a.js", "https://jeremyjia.github.io/Games/issues/4/c4.js");
    }
    else{ 
	var d = bl$( "div_ID_4_I4C4" );
	_on_off_div( this ,d);
    }
}

**Comment by littleflute** [comment]
var s = "_issue14: v0.0. 11 ";
var d = blo0.blMDiv(document.body,"122", s, 300,100,500,400, blGrey[5]); 
d.v = blo0.blDiv(d, d.id + "v", "v2", blGrey[1]);
var ipath = "https://littleflute.github.io/cchess0/cchess/images/";
var style = d.v.style;
  style.position = "relative";
  style.width = 511+ "px";
  style.height = 511+ "px";
  style.background = "url(" + ipath+ "board.jpg)";
var img = document.createElement("img");
      
      img.style.position = "absolute"; 
      img.style.left = 25;
      img.style.top = 125; 
      img.style.width = 57;
      img.style.height = 57;
      img.style.zIndex = 0; 

      d.v.appendChild(img);
_on_off_div(null,d);

**Comment by littleflute** [comment]
var t = bl$("myTable");

var bs = t.getElementsByTagName("button");
for(i in bs){
   bs[i].onclick = function(_i){
        return function(){
              alert(_i);
        }
   }(i);
}

**Comment by littleflute** [comment]
var t = bl$("myTable");

var bs = t.getElementsByTagName("button");
for(i in bs){
   bs[i].style.backgroundColor = "lightblue";
   bs[i].onclick = function(_i,_this){
        return function(){
               var a = _this.parentElement.parentElement.innerHTML;
               var b = a.split("</td>");
               var c = b[2].split("<td>");
             //  alert(c[1]);
 
               var w = {};
	       w._2do = function(txt){  alert(txt); }
	       var urlLrc = "delete";
	       blo0.blAjx(w,urlLrc);
        }
   }(i,bs[i]);
}

**Comment by littleflute** [comment]
var t = bl$("myTable");

var bs = t.getElementsByTagName("button");
for(i in bs){
   bs[i].style.backgroundColor = "lightblue";
   bs[i].onclick = function(_i,_this){
        return function(){
               var a = _this.parentElement.parentElement.innerHTML;
               var b = a.split("</td>");
               var c = b[2].split("<td>");
             //  alert(c[1]);
 
               var w = {};
	       w._2do = function(txt){  alert(txt); }
	       var urlLrc = "delete?address='"+c[1]+"'";
	       blo0.blAjx(w,urlLrc);
        }
   }(i,bs[i]);
}

**Comment by littleflute** [comment]
var d = bl$("div_ID_4_I4C4");
alert(d.addTimerUser)

**Comment by littleflute** [comment]
var s = "blog_i#955: v0.0. 11";
var d = blo0.blMDiv(document.body,"id_mdiv_loadIssue_blog_955", s, 300,100,500,400, blGrey[5]);
function _loadIssue (o) { eval(o.body); }
var url = "https://api.github.com/repos/littleflute/blog/issues/955";
w3.getHttpObject(url, _loadIssue );
_on_off_div(null,d);

**Comment by littleflute** [comment]
var s = "plx: v0.0. 12";
var d = blo0.blMD("id_mdiv_load_plx", s,    300,100,500,400, blGrey[5]); 



_on_off_div(null,d);

**Comment by littleflute** [comment]
var xhr = new XMLHttpRequest();
xhr.withCredentials = true;

xhr.addEventListener("readystatechange", function() {
  if(this.readyState === 4) {
    alert(this.responseText + "abc");
  }
});

xhr.open("GET", "http://localhost:3000/api/getPlayer?id=-1507897597");
xhr.setRequestHeader("Authorization", "Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VyIjp7InYiOiJ2MC4xMyIsImlkIjoxLCJ1c2VybmFtZSI6InlvbmdsaW5nIiwiZW1pYWwiOiJ5b25nbGluZy5odWFuZ0Bncm91cDYuaW8ifSwiaWF0IjoxNTkwNjEwNDgzLCJleHAiOjE1OTA2MTQwODN9.Ht3bmDBb3AkYgaNfqjmH3aGdplq02ffxymwuRJrnYu0");

xhr.send();

**Comment by littleflute** [comment]
aaa
